global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "banvetau-prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]
    metrics_path: "/metrics"

  - job_name: "banvetau-springboot"
    scrape_interval: 5s
    static_configs:
      - targets: [ "host.docker.internal:1122" ]
    metrics_path: "/actuator/prometheus"

  - job_name: "banvetau-node-exporter"
    scrape_interval: 5s
    static_configs:
      - targets: [ "host.docker.internal:9100" ]

  - job_name: "banvetau-mysql-exporter"
    scrape_interval: 5s
    static_configs:
      - targets: [ "host.docker.internal:9104" ]
    metrics_path: "/metrics"

  - job_name: "banvetau-redis-exporter"
    scrape_interval: 5s
    static_configs:
      - targets: [ "host.docker.internal:9121" ]
    metrics_path: "/metrics"

#  - job_name: "banvetau-logstash-exporter"
#    scrape_interval: 5s
#    static_configs:
#      - targets: [ "host.docker.internal:9304" ]
#    metrics_path: "/metrics"