version: '3.2'

networks:
  pre-event-network:
    driver: bridge

services:
  ticket-service:
    build:
      context: ..
      dockerfile: environment/Dockerfile
    volumes:
      - ../Ticket-start/target/Ticket-start-1.0-SNAPSHOT.jar:/app/app.jar
    working_dir: /app
    ports:
      - "1122:1122"
    environment:
      - SERVER_PORT=1122
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3316/vetautet
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE=20
      - SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE=5
      - SPRING_REDIS_SENTINEL_MASTER=mymaster
      - SPRING_REDIS_SENTINEL_NODES=redis-sentinel1:26379,redis-sentinel2:26379,redis-sentinel3:26379
      - SPRING_REDIS_PASSWORD=123456
    networks:
      - pre-event-network

  mysql:
    image: mysql:8.0
    container_name: pre-event-mysql
    volumes:
      - mysql_data3:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d/
    command: [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
        '--skip-character-set-client-handshake', # Buộc tất cả kết nối sử dụng utf8mb4
    ]
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: vetautet
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
    ports:
      - "3316:3306"
    networks:
      - pre-event-network

  #Redis
  redis:
    container_name: pre-event-redis
    image: redis:latest
    ports:
      - "6319:6379"
    networks:
      - pre-event-network

  prometheus:
    image: prom/prometheus:latest
    container_name: pre-event-prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "9090:9090"
    networks:
      - pre-event-network

  grafana:
    image: grafana/grafana
    container_name: pre-event-grafana
    hostname: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SING_UP=false
      - GF_SERVER_DOMAIN=localhost
      #enable logger
      - GF_LOG_MODE=console file
      - GF_LOG_FILTERS=alerting.notifier.slack:debug alermanager:debug ngalert:debug

    volumes:
      - ./grafana-storage:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - pre-event-network

  node-exporter:
    image: prom/node-exporter:latest
    container_name: pre-event-node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - --path.procfs=/host/proc
      - --path.rootfs=/rootfs
      - --path.sysfs=/host/sys
      - --collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)
    ports:
      - "9100:9100"
    networks:
      - pre-event-network

  mysqld-exporter:
    image: prom/mysqld-exporter
    container_name: pre-event-mysqld-exporter
    ports:
      - "9104:9104"
    command:
      - '--collect.engine_innodb_status'
      - '--collect.info_schema.processlist'
      - '--collect.info_schema.tables'
      - '--collect.info_schema.query_response_time'
      - '--collect.perf_schema.file_events'
      - '--collect.perf_schema.eventsstatements'
      - '--collect.perf_schema.indexiowaits'
      - '--collect.global_status'
      #      - '--ignore-tables'
      - '--config.my-cnf=/etc/mysql/.my.cnf'
    volumes:
      - ./mysqld-exporter/.my.cnf:/etc/mysql/.my.cnf
    environment:
      - DATA_SOURCE_NAME=root:123456@tcp(mysql:3306)/
    depends_on:
      - mysql
    networks:
      - pre-event-network

  redis-exporter:
    image: oliver006/redis_exporter
    command: -redis.addr redis://redis:6379
    ports:
      - 9121:9121
    networks:
      - pre-event-network

  elasticsearch:
    image: elasticsearch:7.17.25
    container_name: pre-event-elasticsearch
    volumes:
      - ./elk/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
    networks:
      - pre-event-network

  logstash:
    image: logstash:7.17.25
    container_name: pre-event-logstash
    volumes:
      - ./elk/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./elk/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5044:5044"
      - "5033:5000/tcp"
      - "5022:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - pre-event-network
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:7.17.25
    container_name: pre-event-kibana
    volumes:
      - ./elk/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    networks:
      - pre-event-network
    depends_on:
      - elasticsearch

#  logstash-exporter:
#    image: alxrem/prometheus-logstash-exporter
#    container_name: pre-event-logstash-exporter
#    command: ["-logstash.host", "logstash"]
#    platform: linux/arm64/v8
#    environment:
#      LOGSTASH_URI: "http://logstash:9600" # Kết nối tới Logstash API
#    ports:
#      - "9304:9304" # Cổng Logstash Exporter cho Prometheus
#    networks:
#      - pre-event-network
#    depends_on:
#      - logstash

volumes:
  mysql_data3: